import requests
import json
import uuid
import re
from flask import current_app

class AIService:
    @staticmethod
    def generate_form(prompt, current_form=None):
        """
        Generates a form structure using the configured LLM.
        """
        api_url = current_app.config.get("LLM_API_URL")
        model = current_app.config.get("LLM_MODEL")
        
        system_prompt = """
        You are an AI Form Builder assistant. Your goal is to generate a structured JSON object for a web form based on the user's request.
        
        ALLOWED FIELD TYPES:
        - short_text
        - paragraph
        - number
        - date
        - dropdown
        - checkboxes
        - radio
        - file_upload
        - email
        - mobile
        - url
        
        JSON SCHEMA:
        {
          "sections": [
            {
              "title": "Section Title",
              "order_index": 0,
              "questions": [
                {
                  "question_text": "Question Label",
                  "field_type": "one_of_allowed_types",
                  "is_required": true/false,
                  "order_index": 0,
                  "options": [ // Only for dropdown, checkboxes, radio
                    {"option_label": "Label", "option_value": "value"}
                  ],
                  "visibility_rules": [] // Optional logic
                }
              ]
            }
          ]
        }
        
        RULES:
        1. Return ONLY pure JSON. No markdown formatting.
        2. Ensure order_index starts at 0 and is sequential.
        3. Do not include IDs; they will be generated by the backend.
        4. If logic is implied (e.g. 'if yes show more'), try to generate visibility_rules.
        """
        
        messages = [
            {"role": "system", "content": system_prompt},
        ]
        
        if current_form:
            messages.append({"role": "user", "content": f"Current form structure: {json.dumps(current_form)}"})
            messages.append({"role": "user", "content": f"Please update the form based on this instruction: {prompt}"})
        else:
            messages.append({"role": "user", "content": f"Create a new form for: {prompt}"})
            
        payload = {
            "model": model,
            "messages": messages,
            "stream": False,
            "temperature": 0.7
        }
        
        try:
            response = requests.post(api_url + "/chat/completions", json=payload, timeout=60)
            response.raise_for_status()
            result = response.json()
            content = result['choices'][0]['message']['content']
            
            # Sanitize JSON output
            json_str = AIService._extract_json(content)
            form_data = json.loads(json_str)
            
            # Post-process: Add UUIDs and normalize indices
            AIService._post_process_form(form_data)
            
            return form_data
        except Exception as e:
            current_app.logger.error(f"LLM Error: {str(e)}")
            raise e

    @staticmethod
    def analyze_form(form_data):
        """
        Analyzes a form structure for design issues and suggests improvements.
        """
        api_url = current_app.config.get("LLM_API_URL")
        model = current_app.config.get("LLM_MODEL")
        
        system_prompt = """
        You are a UX Expert and AI Form Builder assistant. Analyze the given form structure (JSON) and provide:
        1. A list of potential issues (e.g., vague labels, missing help text, too many fields).
        2. Strategic suggestions for improvement.
        3. A score from 0-100 for the overall design quality.
        
        Return ONLY a JSON object:
        {
          "score": 85,
          "issues": [
            {"type": "clarity", "field_id": "optional_id", "message": "Description of the issue"}
          ],
          "suggestions": [
            "Specific improvement suggestion"
          ]
        }
        """
        
        payload = {
            "model": model,
            "messages": [
                {"role": "system", "content": system_prompt},
                {"role": "user", "content": json.dumps(form_data)}
            ],
            "stream": False,
            "temperature": 0.4
        }
        
        try:
            response = requests.post(api_url + "/chat/completions", json=payload, timeout=60)
            response.raise_for_status()
            result = response.json()
            content = result['choices'][0]['message']['content']
            
            json_str = AIService._extract_json(content)
            return json.loads(json_str)
        except Exception as e:
            current_app.logger.error(f"Form Analysis Error: {str(e)}")
            # Return a basic fallback analysis if AI fails
            return {
                "score": 0,
                "issues": [{"type": "error", "message": f"AI analysis failed: {str(e)}"}],
                "suggestions": ["Please try again later."]
            }

    @staticmethod
    def get_suggestions(current_form):
        """
        Provides suggestions for new fields based on current form content.
        """
        api_url = current_app.config.get("LLM_API_URL")
        model = current_app.config.get("LLM_MODEL")
        
        system_prompt = """
        You are an AI Form Builder. Based on the current form structure, suggest 3-5 additional fields that would be useful.
        Return ONLY a JSON object:
        {
          "suggestions": [
            {"label": "Suggested Label", "field_type": "short_text/number/dropdown/...", "reason": "Why this is useful"}
          ]
        }
        """
        
        payload = {
            "model": model,
            "messages": [
                {"role": "system", "content": system_prompt},
                {"role": "user", "content": json.dumps(current_form)}
            ],
            "stream": False,
            "temperature": 0.7
        }
        
        try:
            response = requests.post(api_url + "/chat/completions", json=payload, timeout=60)
            response.raise_for_status()
            result = response.json()
            content = result['choices'][0]['message']['content']
            
            json_str = AIService._extract_json(content)
            return json.loads(json_str)
        except Exception as e:
            current_app.logger.error(f"Suggestions Error: {str(e)}")
            return {"suggestions": []}

    @staticmethod
    def _extract_json(text):
        """
        Extracts JSON from a string that might contain markdown blocks.
        """
        if not text:
            return "{}"
            
        # Try to find content between ```json and ```
        match = re.search(r'```(?:json)?\s*(.*?)\s*```', text, re.DOTALL)
        if match:
            return match.group(1).strip()
        
        # Fallback: try to find anything between the first { and last }
        start = text.find('{')
        end = text.rfind('}')
        if start != -1 and end != -1:
            return text[start:end+1]
        
        return text.strip()
