import requests
import json
import uuid
import re
from flask import current_app

class AIService:
    @staticmethod
    def generate_form(prompt, current_form=None):
        """
        Generates a form structure using the configured LLM.
        """
        api_url = current_app.config.get("LLM_API_URL")
        model = current_app.config.get("LLM_MODEL")
        
        system_prompt = """
        You are an AI Form Builder assistant. Your goal is to generate a structured JSON object for a web form based on the user's request.
        
        ALLOWED FIELD TYPES:
        - short_text
        - paragraph
        - number
        - date
        - dropdown
        - checkboxes
        - radio
        - file_upload
        - email
        - mobile
        - url
        
        JSON SCHEMA:
        {
          "sections": [
            {
              "title": "Section Title",
              "order_index": 0,
              "questions": [
                {
                  "question_text": "Question Label",
                  "field_type": "one_of_allowed_types",
                  "is_required": true/false,
                  "order_index": 0,
                  "options": [ // Only for dropdown, checkboxes, radio
                    {"option_label": "Label", "option_value": "value"}
                  ],
                  "visibility_rules": [] // Optional logic
                }
              ]
            }
          ]
        }
        
        RULES:
        1. Return ONLY pure JSON. No markdown formatting.
        2. Ensure order_index starts at 0 and is sequential.
        3. Do not include IDs; they will be generated by the backend.
        4. If logic is implied (e.g. 'if yes show more'), try to generate visibility_rules.
        """
        
        messages = [
            {"role": "system", "content": system_prompt},
        ]
        
        if current_form:
            messages.append({"role": "user", "content": f"Current form structure: {json.dumps(current_form)}"})
            messages.append({"role": "user", "content": f"Please update the form based on this instruction: {prompt}"})
        else:
            messages.append({"role": "user", "content": f"Create a new form for: {prompt}"})
            
        payload = {
            "model": model,
            "messages": messages,
            "stream": False,
            "temperature": 0.7
        }
        
        try:
            response = requests.post(api_url + "/chat/completions", json=payload, timeout=60)
            response.raise_for_status()
            result = response.json()
            content = result['choices'][0]['message']['content']
            
            # Sanitize JSON output
            json_str = AIService._extract_json(content)
            form_data = json.loads(json_str)
            
            # Post-process: Add UUIDs and normalize indices
            AIService._post_process_form(form_data)
            
            return form_data
        except Exception as e:
            current_app.logger.error(f"LLM Error: {str(e)}")
            raise e

    @staticmethod
    def _extract_json(text):
        """
        Extracts JSON from a string that might contain markdown blocks.
        """
        # Try to find content between ```json and ```
        match = re.search(r'```json\s*(.*?)\s*```', text, re.DOTALL)
        if match:
            return match.group(1)
        
        # Fallback: try to find anything between the first { and last }
        match = re.search(r'\{.*\}', text, re.DOTALL)
        if match:
            return match.group(0)
        
        return text

    @staticmethod
    def _post_process_form(form_data):
        """
        Adds UUIDs and ensures order indices are correct.
        """
        if "sections" not in form_data:
            form_data["sections"] = []
            
        for s_idx, section in enumerate(form_data["sections"]):
            section["id"] = str(uuid.uuid4())
            section["order_index"] = s_idx
            
            if "questions" not in section:
                section["questions"] = []
                
            for q_idx, question in enumerate(section["questions"]):
                question["id"] = str(uuid.uuid4())
                question["order_index"] = q_idx
                
                # Normalize field types if LLM used synonyms
                type_map = {
                    "input": "short_text",
                    "textarea": "long_text",
                    "paragraph": "long_text",
                    "select": "dropdown",
                    "boolean": "radio",
                    "checkboxes": "checkbox"
                }
                if question.get("field_type") in type_map:
                    question["field_type"] = type_map[question["field_type"]]
                
                if "options" in question and question["options"]:
                    for option in question["options"]:
                        option["id"] = str(uuid.uuid4())
                        if "option_value" not in option:
                            option["option_value"] = option.get("option_label", "").lower().replace(" ", "_")
